# Copyright 2019-2025 Chris Croome
#
# This file is part of the Webarchitects phpMyAdmin Ansible role.
#
# The Webarchitects phpMyAdmin Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects phpMyAdmin Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects phpMyAdmin Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Configure phpMyAdmin
  block:

    - name: DocumentRoot .htaccess in place
      ansible.builtin.copy:
        src: files/htaccess.root
        dest: "{{ phpmyadmin_docroot }}/.htaccess"
        owner: "{{ phpmyadmin_user }}"
        group: "{{ phpmyadmin_group }}"
        mode: "0644"

    - name: Check if the database contains tables
      community.mysql.mysql_query:
        login_unix_socket: "{{ phpmyadmin_dbsocket }}"
        login_db: "{{ phpmyadmin_dbname }}"
        query: SHOW TABLES
      register: phpmyadmin_show_tables

    - name: Debug database query
      ansible.builtin.debug:
        var: phpmyadmin_show_tables.query_result
        verbosity: "{% if ansible_check_mode | bool %}2{% else %}3{% endif %}"

    - name: Debug database query result
      ansible.builtin.debug:
        msg:
          - "{{ phpmyadmin_show_tables.query_result | community.general.json_query('[].*[]') }}"
          - "{{ phpmyadmin_show_tables.query_result | community.general.json_query('[].*[]') }} | length "
        verbosity: "{% if ansible_check_mode | bool %}1{% else %}2{% endif %}"

    - name: Database tables present
      community.mysql.mysql_db:
        login_unix_socket: "{{ phpmyadmin_dbsocket }}"
        name: "{{ phpmyadmin_dbname }}"
        state: import
        target: "{{ phpmyadmin_docroot }}/sql/create_tables.sql"
      when: >-
        ( phpmyadmin_show_tables.query_result is not defined ) or
        ( phpmyadmin_show_tables.query_result | community.general.json_query('[].*[]') | length == 0 )

    - name: "Ensure that ~/.ansible is owned by and in the group of {{ phpmyadmin_user }}"
      ansible.builtin.file:
        path: "{{ phpmyadmin_home }}/.ansible"
        recurse: true
        owner: "{{ phpmyadmin_user }}"
        group: "{{ phpmyadmin_group }}"

    # TODO Replace this with the ansible.builtin.find module
    # https://docs.phpmyadmin.net/en/latest/config.html#web-dirs
    - name: Get a list of sub-directories
      ansible.builtin.shell: |
        set -e -o pipefail
        find . -maxdepth 1 -type d | grep -v ^\.$ | sed 's/\.\///' | grep -v ^js$ | grep -v ^themes$ | grep -v ^vendor$
      args:
        chdir: "{{ phpmyadmin_docroot }}"
        executable: "{{ ansible_local.bash.path }}"
      environment: "{{ phpmyadmin_env }}"
      become: true
      become_user: "{{ phpmyadmin_user }}"
      check_mode: false
      changed_when: false
      register: phpmyadmin_subdirs

    - name: Find a list of sub-directories of the DocumentRoot
      ansible.builtin.find:
        path: "{{ phpmyadmin_docroot }}"
        depth: 1
        file_type: directory
        hidden: true
      register: phpmyadmin_find

    - name: Set a fact for the DocumentRoot sub-directories
      ansible.builtin.set_fact:
        phpmyadmin_subdirs: "{{ phpmyadmin_find | community.general.json_query('files[].path') }}"

    - name: Debug find sub-directories
      ansible.builtin.debug:
        msg: "{{ phpmyadmin_find | community.general.json_query('files[].path') }}"
        verbosity: "{% if ansible_check_mode | bool %}1{% else %}2{% endif %}"

    - name: Sub-directory .htaccess files in place to deny access
      ansible.builtin.copy:
        src: files/htaccess.deny
        dest: "{{ phpmyadmin_dir }}/.htaccess"
        owner: "{{ phpmyadmin_user }}"
        group: "{{ phpmyadmin_group }}"
        mode: "0644"
      when:
        - phpmyadmin_dir | basename !="js"
        - phpmyadmin_dir | basename !="themes"
        - phpmyadmin_dir | basename !="vendor"
      loop: "{{ phpmyadmin_subdirs }}"
      loop_control:
        loop_var: phpmyadmin_dir
        label: "{{ phpmyadmin_dir | basename }}"

    - name: Deny bots robots.txt in place
      ansible.builtin.copy:
        src: robots.txt
        dest: "{{ phpmyadmin_docroot }}/robots.txt"
        owner: "{{ phpmyadmin_user }}"
        group: "{{ phpmyadmin_group }}"
        mode: "0644"

    - name: Generate blowfish secret for cookies
      ansible.builtin.shell: |
        set -e -o pipefail
        pwgen -sn 32 1 > {{ phpmyadmin_private }}/.blowfish.secret && chmod 400 {{ phpmyadmin_private }}/.blowfish.secret
      args:
        creates: "{{ phpmyadmin_private }}/.blowfish.secret"
        executable: "{{ ansible_local.bash.path }}"
      environment: "{{ phpmyadmin_env }}"
      become: true
      become_user: "{{ phpmyadmin_user }}"
      check_mode: false

    - name: Set a variable for the base64 encoded .blowfish.secret value
      ansible.builtin.slurp:
        src: "{{ phpmyadmin_private }}/.blowfish.secret"
      register: phpmyadmin_blowfish_b64encoded

    - name: Set a fact for the blowfish secret
      ansible.builtin.set_fact:
        phpmyadmin_blowfish_secret: "{{ phpmyadmin_blowfish_b64encoded['content'] | b64decode | trim }}"

    - name: Config file present
      ansible.builtin.template:
        src: templates/config.inc.php.j2
        dest: "{{ phpmyadmin_docroot }}/config.inc.php"
        owner: "{{ phpmyadmin_user }}"
        group: "{{ phpmyadmin_group }}"
        mode: "0640"

  tags:
    - phpmyadmin
...
