---
# This isn't currently used as phpMyAdmin is downloaded using
# git rather than a GPG signed archive.

- name: Install pmpMyAdmin GPG public key
  block:

    - name: The phpMyAdmin GPG public key is present
      copy:
        src: files/phpmyadmin.pub
        dest: "{{ phpmyadmin_private }}/phpmyadmin.pub"
      become: true
      become_user: "{{ phpmyadmin_user }}"

    - name: "phpMyAdmin GPG public key imported for {{ phpmyadmin_user }}"
      command: "gpg --no-tty --import {{ phpmyadmin_private }}/phpmyadmin.pub"
      register: phpmyadmin_gpg_key_import
      changed_when: "'not changed' not in phpmyadmin_gpg_key_import.stderr"
      become: true
      become_user: "{{ phpmyadmin_user }}"

    - name: "phpMyAdmin GPG public key imported for root"
      command: "gpg --no-tty --import {{ phpmyadmin_private }}/phpmyadmin.pub"
      register: phpmyadmin_gpg_key_import_root
      changed_when: "'not changed' not in phpmyadmin_gpg_key_import_root.stderr"

  when: '"no such user" not in phpmyadmin_user_check.stderr'
  tags:
    - phpmyadmin
...
