---
- name: Database tables present
  mysql_db:
    name: "{{ phpmyadmin_db }}"
    state: import
    target: "{{ phpmyadmin_html }}/sql/create_tables.sql"
  tags:
    - phpmyadmin

- name: Run database upgrades
  block:

    - name: upgrade_tables_mysql_4_1_2+.sql
      mysql_db:
        name: "{{ phpmyadmin_db }}"
        state: import
        target: "{{ phpmyadmin_html }}/sql/create_tables.sql"
      when: phpmyadmin_debian_version is version_compare('4.1.2', '>=')
      tags:
        - phpmyadmin

    - name: upgrade_column_info_4_3_0+.sql
      mysql_db:
        name: "{{ phpmyadmin_db }}"
        state: import
        target: "{{ phpmyadmin_html }}/sql/create_tables.sql"
      when: phpmyadmin_debian_version is version_compare('4.3.0', '>=')
      tags:
        - phpmyadmin

    - name: upgrade_tables_4_7_0+.sql
      mysql_db:
        name: "{{ phpmyadmin_db }}"
        state: import
        target: "{{ phpmyadmin_html }}/sql/create_tables.sql"
      when: phpmyadmin_debian_version is version_compare('4.6.5', '>=')
      tags:
        - phpmyadmin

  when: phpmyadmin_debian_version is defined
...
