---
- name: Clone the repo
  git:
    repo: https://github.com/phpmyadmin/phpmyadmin.git
    dest: "{{ phpmyadmin_html }}"
    version: "{{ phpmyadmin_version }}"
    clone: true
    force: true
    verify_commit: true
  tags:
    - phpmyadmin

- name: .htaccess in place
  copy:
    src: files/htaccess.root
    dest: "{{ phpmyadmin_html }}/.htaccess"
  tags:
    - phpmyadmin

- name: Directories for saves and uploads present
  file:
    path: "{{ dir }}"
    state: directory
  loop:
    - "{{ phpmyadmin_html_upload_dir }}"
    - "{{ phpmyadmin_html_save_dir }}"
  loop_control:
    loop_var: dir
  tags:
    - phpmyadmin

- name: .htaccess in place for upload and saves directory
  copy:
    src: files/htaccess.deny
    dest: "{{ dir }}/.htaccess"
  loop:
    - "{{ phpmyadmin_html_upload_dir }}"
    - "{{ phpmyadmin_html_save_dir }}"
  loop_control:
    loop_var: dir
  tags:
    - phpmyadmin

- name: Generate blowfish secret for cookies
  command: pwgen -sn 32 1
  register: phpmyadmin_blowfish_gen
  tags:
    - phpmyadmin

- name: Set a fact for the blowfish secret
  set_fact:
    phpmyadmin_blowfish_secret: "{{ phpmyadmin_blowfish_gen.stdout }}"
  tags:
    - phpmyadmin

- name: Generate the config.inc.php file
  template:
    src: templates/config.inc.php.j2
    dest: "{{ phpmyadmin_html }}/config.inc.php"
  tags:
    - phpmyadmin
...
