---
- name: Required packages present
  apt:
    pkg:
      - aptitude
      - git
      - pwgen
    state: present
  tags:
    - phpmyadmin

- name: Include backwards compatibility tasks
  include_tasks: compat.yml
  tags:
    - phpmyadmin

# TODO Additional checks on variables could be added
- name: Check that required variables are defined
  assert:
    that:
      - phpmyadmin_user is defined
      - phpmyadmin_dbname is defined
      - phpmyadmin_dbuser is defined
      - phpmyadmin_dbpass is defined
      - phpmyadmin_dbhost is defined
      - phpmyadmin_dbport is defined
      - phpmyadmin_dbsocket is defined
      - phpmyadmin_url is defined
      - phpmyadmin_home is defined
      - phpmyadmin_tmp is defined
      - phpmyadmin_private is defined
      - phpmyadmin_docroot is defined
      - phpmyadmin_lang is defined
  tags:
    - phpmyadmin

- name: "Check if the phpMyAdmin {{ phpmyadmin_user }} user account exists"
  shell: "id {{ phpmyadmin_user }} && echo true || echo false"
  check_mode: false
  register: phpmyadmin_user_check
  changed_when: '"no such user" in phpmyadmin_user_check.stderr'
  tags:
    - phpmyadmin

- name: Only install or upgrade phpMyAdmin if the user account exists
  block:

    - name: Check if a Debian package is installed
      shell: "aptitude versions phpmyadmin | grep -q ^i && echo INSTALLED || echo NOTFOUND"
      check_mode: false
      register: phpmyadmin_debian_installed
      changed_when: '"INSTALLED" in phpmyadmin_debian_installed.stdout'

    - name: Upgrade from a Debian package version
      include_tasks: upgrade_from_deb.yml
      when: ( phpmyadmin_debian_installed is defined ) and ( phpmyadmin_debian_installed.stdout == "INSTALLED" )

    - name: Check for package.json
      stat:
        path: "{{ phpmyadmin_html }}/package.json"
      register: phpmyadmin_package_json

    - name: Load variables from package.json if it exists
      include_tasks: version.yml
      when: ( phpmyadmin_package_json is defined ) and ( phpmyadmin_package_json.stat.exists )

    - name: Include tasks to ensure that the required version of the phpMyAdmin source code is present
      include_tasks: phpmyadmin.yml
      when: ( not phpmyadmin_package_json.stat.exists ) or ( phpmyadmin_installed_version is defined and phpmyadmin_installed_version != phpmyadmin_version )

  when: '"no such user" not in phpmyadmin_user_check.stderr'
  tags:
    - phpmyadmin
...
