---
- name: Install and upgrade phpMyAdmin
  block:

    - name: Required packages present
      apt:
        pkg:
          - aptitude
          - git
          - gnupg
          - pwgen
        state: present

    # TODO Omit this when everything has been updated
    - name: Include backwards compatibility tasks
      include_tasks: compat.yml

    # TODO Additional checks on variables could be added
    - name: Check that required variables are defined
      assert:
        that:
          - phpmyadmin_user is defined
          - ( phpmyadmin_version is defined ) and ( phpmyadmin_version is regex('^[0-9][.][0-9][.][0-9]{1,2}[.]{0,1}[0-9]{0,2}$') )
          - phpmyadmin_dbname is defined
          - phpmyadmin_dbuser is defined
          - phpmyadmin_dbpass is defined
          - phpmyadmin_dbhost is defined
          - phpmyadmin_dbport is defined
          - phpmyadmin_dbsocket is defined
          - phpmyadmin_url is defined
          - phpmyadmin_home is defined
          - phpmyadmin_tmp is defined
          - phpmyadmin_private is defined
          - phpmyadmin_docroot is defined
          - phpmyadmin_lang is defined

    - name: "Populate the getent_passwd array for {{ inventory_hostname }}"
      getent:
        database: passwd
        split: ':'

    - name: "Fail if the {{ phpmyadmin_user }} user account doesn't exist"
      fail:
        msg: "The {{ phpmyadmin_user }} user account doesn't exist on {{ inventory_hostname }}"
      when: phpmyadmin_user not in getent_passwd

    # TODO This is to upgrade from phpMyAdmin in Stretch, Buster didn't ship it but Bullseye does
    - name: Check if a Debian package is installed
      shell: "aptitude versions phpmyadmin | grep -q ^i && echo INSTALLED || echo NOTFOUND"
      check_mode: false
      register: phpmyadmin_debian_installed
      changed_when: '"INSTALLED" in phpmyadmin_debian_installed.stdout'

    - name: Upgrade from a Debian package version
      include_tasks: upgrade_from_deb.yml
      when: ( phpmyadmin_debian_installed is defined ) and ( phpmyadmin_debian_installed.stdout == "INSTALLED" )

    - name: Check for package.json
      stat:
        path: "{{ phpmyadmin_docroot }}/package.json"
      register: phpmyadmin_package_json

    - name: When phpMyAdmin is already installed upgrade if needed
      block:

        - name: Load variables from package.json if it exists
          include_tasks: version.yml

        - name: Include tasks to ensure that the required version of the phpMyAdmin source code is present
          include_tasks: phpmyadmin.yml
          when: ( phpmyadmin_installed_version is defined ) and ( phpmyadmin_installed_version != phpmyadmin_version )

      when: ( phpmyadmin_package_json is defined ) and ( phpmyadmin_package_json.stat.exists )

    - name: Include tasks to ensure that the required version of the phpMyAdmin source code is present
      include_tasks: phpmyadmin.yml
      when: ( phpmyadmin_package_json is not defined ) or ( not phpmyadmin_package_json.stat.exists )

  tags:
    - phpmyadmin
...
