---
- name: "Write phpmyadmin_version variable to {{ phpmyadmin_version_file }}"
  template:
    src: templates/phpmyadmin_version.j2
    dest: "{{ phpmyadmin_version_file }}"
  tags:
    - phpmyadmin

- name: "Stat {{ phpmyadmin_version_file }}"
  stat:
    path: "{{ phpmyadmin_version_file }}"
  register: phpmyadmin_version_file
  tags:
    - phpmyadmin

# https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git
- name: phpMyAdmin repo present
  git:
    repo: https://github.com/phpmyadmin/phpmyadmin.git
    dest: "{{ phpmyadmin_html }}"
    version: "{{ phpmyadmin_version }}"
    clone: true
    update: true
    verify_commit: true
  tags:
    - phpmyadmin

- name: Chown the files
  file:
    path: "{{ phpmyadmin_html }}"
    recurse: true
    owner: "{{ phpmyadmin_user }}"
    group: "{{ phpmyadmin_user }}"
  tags:
    - phpmyadmin

- name: When phpmyadmin_version_file has changed
  block:

    - name: composer update for phpMyAdmin
      command: composer update --no-dev
      args:
        chdir: "{{ phpmyadmin_html }}"
      become: true
      become_user: "{{ phpmyadmin_user }}"
      tags:
        - phpmyadmin

    - name: composer packages for two factor authentication present
      command: composer require --update-no-dev pragmarx/google2fa-qrcode
      args:
        chdir: "{{ phpmyadmin_html }}"
      become: true
      become_user: "{{ phpmyadmin_user }}"
      tags:
        - phpmyadmin

    - name: yarn install for phpMyAdmin
      command: yarn install
      args:
        chdir: "{{ phpmyadmin_html }}"
      become: true
      become_user: "{{ phpmyadmin_user }}"
      tags:
        - phpmyadmin

  when: phpmyadmin_version_file is changed

- name: .htaccess in place
  copy:
    src: files/htaccess.root
    dest: "{{ phpmyadmin_html }}/.htaccess"
  tags:
    - phpmyadmin

# https://docs.phpmyadmin.net/en/latest/config.html#web-dirs
- name: Get a list of sub-directories
  shell: find . -maxdepth 1 -type d | grep -v ^\.$ | sed 's/\.\///'
  args:
    chdir: "{{ phpmyadmin_html }}"
  become: true
  become_user: "{{ phpmyadmin_user }}"
  changed_when: false
  register: phpmyadmin_subdirs
  tags:
    - phpmyadmin

- name: .htaccess files in place to deny direct access to sub-directories
  copy:
    src: files/htaccess.deny
    dest: "{{ phpmyadmin_html }}/{{ dir }}/.htaccess"
  loop: "{{ phpmyadmin_subdirs.stdout_lines }}"
  loop_control:
    loop_var: dir
  tags:
    - phpmyadmin

- name: Stat the blowfish secret file
  stat:
    path: "{{ phpmyadmin_private }}/blowfish_secret.inc.php"
  register: phpmyadmin_private_blowfish_secret_file
  tags:
    - phpmyadmin

- name: Generate the blowfish secret file
  block:

    - name: Generate blowfish secret for cookies
      command: pwgen -sn 32 1
      register: phpmyadmin_blowfish_gen
      tags:
        - phpmyadmin

    - name: Set a fact for the blowfish secret
      set_fact:
        phpmyadmin_blowfish_secret: "{{ phpmyadmin_blowfish_gen.stdout }}"
      tags:
        - phpmyadmin

    - name: Blowfish secret file present
      template:
        src: templates/blowfish_secret.inc.php.j2
        dest: "{{ phpmyadmin_private }}/blowfish_secret.inc.php"
      tags:
        - phpmyadmin

  when: phpmyadmin_private_blowfish_secret_file.stat.exists == False
...
