# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects phpMyAdmin Ansible role.
#
# The Webarchitects phpMyAdmin Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects phpMyAdmin Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects phpMyAdmin Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Download and install phpMyAdmin
  block:

    - name: .ansible directory present
      ansible.builtin.file:
        path: "{{ phpmyadmin_home }}/.ansible"
        state: directory
        owner: "{{ phpmyadmin_user }}"
        group: "{{ phpmyadmin_group }}"
        mode: "0700"

    - name: GPG keys present
      ansible.builtin.copy:
        src: "files/{{ key }}"
        dest: "{{ phpmyadmin_private }}/{{ key }}"
        owner: "{{ phpmyadmin_user }}"
        group: "{{ phpmyadmin_group }}"
        mode: "0600"
      loop:
        - github.asc
        - ibennetch.asc
      loop_control:
        loop_var: key
      become: true
      become_user: "{{ phpmyadmin_user }}"

    - name: GitHub GPG public key imported
      ansible.builtin.command: "gpg --import {{ phpmyadmin_private }}/{{ key }}"
      register: phpmyadmin_gpg_import
      changed_when: ( "not changed" not in phpmyadmin_gpg_import.stderr )
      check_mode: false
      loop:
        - github.asc
        - ibennetch.asc
      loop_control:
        loop_var: key
      become: true
      become_user: "{{ phpmyadmin_user }}"

    - name: Convert the phpMyAdmin version string to a git tag
      ansible.builtin.set_fact:
        phpmyadmin_git_tag: "{{ phpmyadmin_proposed | regex_replace('^', 'RELEASE_') | regex_replace('[.]', '_') }}"

    - name: Debug git tag
      ansible.builtin.debug:
        msg: "Proposed git tag: {{ phpmyadmin_git_tag }}"

    # https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git
    - name: phpMyAdmin repo present
      ansible.builtin.git:
        repo: https://github.com/phpmyadmin/phpmyadmin.git
        dest: "{{ phpmyadmin_docroot }}"
        version: "{{ phpmyadmin_git_tag }}"
        depth: 1
        clone: true
        update: true
        force: true
        verify_commit: true
      become: true
      become_user: "{{ phpmyadmin_user }}"

    - name: Chown the files
      ansible.builtin.file:
        path: "{{ phpmyadmin_docroot }}"
        recurse: true
        owner: "{{ phpmyadmin_user }}"
        group: "{{ phpmyadmin_group }}"

  tags:
    - phpmyadmin
...
