---
- name: Get the version of the Debian package which is installed
  block:

    - shell: "aptitude versions phpmyadmin | grep ^i | awk '{ print $2 }' | sed 's/.*://'"
      register: phpmyadmin_debian_version_check

    - name: Set a fact for the phpmyadmin_debian_version
      set_fact:
        phpmyadmin_debian_version: "{{ phpmyadmin_debian_version_check.stdout }}"
      when: phpmyadmin_debian_version_check is defined

  when: ( phpmyadmin_debian_installed is defined ) and ( phpmyadmin_debian_installed.stdout == "INSTALLED" )
  tags:
    - phpmyadmin

- name: Old phpmyadmin deb package absent
  apt:
    pkg: phpmyadmin
    state: absent
    purge: true
  tags:
    - phpmyadmin
...
