---
# TODO Update tasks so they don't use the shell module
- name: Upgrade from a Debian package version
  block:

    - name: Get Debian phpMyAdmin version using aptitude
      ansible.builtin.shell: |
        set -e -o pipefail
        aptitude versions phpmyadmin | grep ^i | awk '{ print $2 }' | sed 's/.*://'
      args:
        executable: "{{ ansible_local.bash.path }}"
      environment: "{{ phpmyadmin_env }}"
      check_mode: false
      changed_when: false
      register: phpmyadmin_debian_version_check

    - name: Set a fact for the phpmyadmin_debian_version
      ansible.builtin.set_fact:
        phpmyadmin_debian_version: "{{ phpmyadmin_debian_version_check.stdout }}"
      when: phpmyadmin_debian_version_check is defined

    - name: Old phpmyadmin deb package absent
      ansible.builtin.apt:
        pkg: phpmyadmin
        state: absent
        purge: true

    - name: Run database upgrades
      block:

        - name: upgrade_tables_mysql_4_1_2+.sql
          community.mysql.mysql_db:
            name: "{{ phpmyadmin_db }}"
            state: import
            target: "{{ phpmyadmin_html }}/sql/create_tables.sql"
          when: phpmyadmin_debian_version is version_compare('4.1.2', '>=')

        - name: upgrade_column_info_4_3_0+.sql
          community.mysql.mysql_db:
            name: "{{ phpmyadmin_db }}"
            state: import
            target: "{{ phpmyadmin_html }}/sql/create_tables.sql"
          when: phpmyadmin_debian_version is version_compare('4.3.0', '>=')

        - name: upgrade_tables_4_7_0+.sql
          community.mysql.mysql_db:
            name: "{{ phpmyadmin_db }}"
            state: import
            target: "{{ phpmyadmin_html }}/sql/create_tables.sql"
          when: phpmyadmin_debian_version is version_compare('4.6.5', '>=')

      when: phpmyadmin_debian_version is defined

  when: ( phpmyadmin_debian_installed is defined ) and ( phpmyadmin_debian_installed.stdout == "INSTALLED" )
  tags:
    - phpmyadmin
...
