---
- name: Check the version of phpMyAdmin installed
  block:

    - name: Slurp package.json
      slurp:
        src: "{{ phpmyadmin_html }}/package.json"
      register: phpmyadmin_vars_b64encoded

    - name: Set facts from package.json variables
      set_fact:
        phpmyadmin_vars: "{{ phpmyadmin_vars_b64encoded['content'] | b64decode | from_json }}"
        phpmyadmin_test: "{{ phpmyadmin_vars_b64encoded['content'] | b64decode | from_json['version'] }}"

    - name: Set facts from package.json variables
      set_fact:
        phpmyadmin_installed_version: "{{ phpmyadmin_vars.version }}"

    - name: Debug loaded variables
      debug:
        msg:
          - "{{ phpmyadmin_vars }}"
          - "Version: {{ phpmyadmin_installed_version }}"
          - "Test: {{ phpmyadmin_test }}"

  tags:
    - phpmyadmin
...
